### Ruta para lotguearse


# Ruta para obtener un  listado de personajes
GET http://localhost:3001/character?apiKey=$2b$10$/3lXIs9V0eM6AnkJ0QgDpeDEP9jz7pgJMq1myzeScltY4RcWzW.Be

# Es la ruta para loguearse wachiin 
GET http://localhost:3001/auth/login?email=sebastian@gmail.com&password=123

         


### Ruta para Retgistrarse
POST http://localhost:3001/auth/register HTTP/1.1
content-type: application/json

{
    "fullname": "Jose Argento",
    "email": "pepiño@gmail.com",
    "password": "123"
}






 